/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yannick' at '26.08.16 10:38' with Gradle 2.13
 *
 * @author yannick, @date 26.08.16 10:38
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
